### ISSUE TITLE
Provide staticly-linked binary?

### ISSUE THREAD

**Issue by shenwei356** [fulcrumgenomics/fqgrep#21]
Tried in the server (centos 7.9) and failed :(

```
$ fqgrep TCAAGTAGTAACTGCCGCGACCTTAGGGCAAGACCTTATGATA  KPN1big_1.fq.gz
fqgrep: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by fqgrep)
```

**Comment by nh13** [comment]
Oh no, that's not good, let me see if I can fix that.  Installed via bioconda, from the packages on the releases page, compile from source?

**Comment by nh13** [comment]
If from the uploaded binaries, I wonder if it would work if I added:

```yml
        env:
          RUSTFLAGS: -C target-feature=+crt-static
          OPENSSL_STATIC: 1
```

to https://github.com/fulcrumgenomics/fqgrep/blob/49882dca71daf7916e8e82acdbba16fa355733d6/.github/workflows/publish.yml#L27-L28
